// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdctskfmvvwesricffko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkY3Rza2ZtdnZ3ZXNyaWNmZmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODY2MzksImV4cCI6MjA2NTk2MjYzOX0.nQjYiqbtNuD2arE6Jm9IB9K6XGLRoVgXKawoe_F3o74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);